#!/usr/bin/env bash
#
# Init repository and environment
#
echo ""
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
echo "Preparing firmware environment, please wait..."
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
echo -e "\n"

# Automate git and config setup
rm -rf qmk_firmware
git clone https://github.com/qmk/qmk_firmware
cd qmk_firmware
make git-submodule
cd keyboards
ln -s ../../config/fatbottomedboard .
cd ../..

# some nice output at the end
echo ""
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =
ls --color -la qmk_firmware/keyboards/fatbottomedboard
echo "Environment completed, configuration linked to QMK.  Type: 'make fatbottomedboard:default' (or './make')to build it"
printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' =

echo -e "\n"
