#!/usr/bin/env bash
#
# Build FatBottomedBoard firmware
#
cd qmk_firmware/
make fatbottomedboard:default
cd - >/dev/null
if [ -f qmk_firmware/fatbottomedboard_default.hex ]; then
    cp qmk_firmware/fatbottomedboard_default.hex fatbottomedboard_babe.hex
fi
