#!/usr/bin/env bash
#
# Build FatBottomedBoard firmware
#
cd qmk_firmware/
make fatbottomedboard:default
cd - >/dev/null
if [ ! -f fatbottomedboard_default.hex ]; then
    ln qmk_firmware/fatbottomedboard_default.hex .
fi
